# Generated by Django 6.0.3 on 2026-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мощность (Вт)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объём (л)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Гарантия'),
        ),
    ]
